---

title: DFO Multispecies Survey Trip Report
subtitle: Newfoundland and Labrador Region
author: "Science Branch"
output: pdf_document
# output: html_document
# End of options to set
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
csl: csl/csas.csl
lot: true
lof: true

---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
# adjust as desired:
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = if (knitr:::is_latex_output()) "knitr-figs-pdf/" else "knitr-figs-docx/",
  cache.path = if (knitr:::is_latex_output()) "knitr-cache-tex/" else "knitr-cache-docx/",
  #fig.asp = 0.618,
  fig.width = 9,
  out.width = "6in",
  echo = FALSE,
#  autodep = TRUE,
#  cache = TRUE,
  cache.comments = FALSE,
  dev = if (knitr:::is_latex_output()) "png" else "png",
  dpi = 180,
  fig.align = "center",
  fig.pos = "htb"
)
```

# ```{r load-libraries, cache=FALSE}
# # add other packages here:
# library(csasdown)
# ```

```{r trip.settings, echo=FALSE}
#BR Added the below and commented out the rest...
library(svDialogs)
library(svGUI)
dfo_fill<-function(){
  res<-list()
  res["PIC"] <- dlg_input("Name of Person in Charge")$res
  res["Vessel.abb"] <- dlg_input("Vessel (ex: TEL)")$res
  if(res["Vessel.abb"]=="TEL"){
    res["Vessel"]<-"Teleost"
  }else{
    res["Vessel"]<-"Alfred Needler"
  }
  res["Trip"] <- dlg_input("Trip (eg. 190)")$res
  res["Start"]<- dlg_input("Start Date (eg. 01 September 2018)")$res
  res["End"]<- dlg_input("End Date (eg. 01 September 2018)")$res
  res["Crew"]<- dlg_input("Scientific Crew (eg. B. Rogers, D. Who)")$res
  res["H_lost"]<- dlg_input("Hours Lost")$res
  
  res
}
trip_sum<-dfo_fill()
```

```{r datasummary, include=FALSE}
library(tidyverse)
library(foreign)

#  read in species codes     
spp_codes <- read_csv("Data/species codes (lookup).csv")
spp_codes$code <- as.numeric(spp_codes$Spc_Code)

#  read in FFS data dbf      
RV.SET <- read.dbf("Data/RV_SET.dbf")
RV.Catch <- read.dbf("Data/RV_CATCH.dbf")

# match spp names to codes 
RV.Catch <- left_join(RV.Catch, spp_codes, by=c("SPECIES" = "code"))

#number of sets
sets <- length(RV.SET)

#divisions surveyed
divs <- as.character(unique(RV.SET$NAFO_DIV))

#Depth range
depth.range <- range(as.numeric(as.character(RV.SET$MEAN_DEPTH)),na.rm=TRUE)

#Number of species encountered.
num.species <- length((unique(RV.Catch$SPECIES)))

#Total catch
total.catch <- RV.Catch %>% 
  summarise(total=sum(WEIGHTC))


```

